package com.chen.system.mapper;

import com.chen.system.entity.SysUserDepart;
import com.chen.system.entity.SysUserDepartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserDepartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    long countByExample(SysUserDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    int deleteByExample(SysUserDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    int insert(SysUserDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    int insertSelective(SysUserDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    List<SysUserDepart> selectByExample(SysUserDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    SysUserDepart selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysUserDepart record, @Param("example") SysUserDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    int updateByExample(@Param("record") SysUserDepart record, @Param("example") SysUserDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    int updateByPrimaryKeySelective(SysUserDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    int updateByPrimaryKey(SysUserDepart record);
}