package com.chen.system.entity;

import java.util.Date;

public class SysDepartRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart_role.id
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart_role.SYS_DEPART_ID
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    private Long sysDepartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart_role.SYS_ROLE_ID
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    private Long sysRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart_role.CREATE_TIME
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart_role.CREATOR
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    private String creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart_role.id
     *
     * @return the value of sys_depart_role.id
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart_role.id
     *
     * @param id the value for sys_depart_role.id
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart_role.SYS_DEPART_ID
     *
     * @return the value of sys_depart_role.SYS_DEPART_ID
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    public Long getSysDepartId() {
        return sysDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart_role.SYS_DEPART_ID
     *
     * @param sysDepartId the value for sys_depart_role.SYS_DEPART_ID
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    public void setSysDepartId(Long sysDepartId) {
        this.sysDepartId = sysDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart_role.SYS_ROLE_ID
     *
     * @return the value of sys_depart_role.SYS_ROLE_ID
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    public Long getSysRoleId() {
        return sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart_role.SYS_ROLE_ID
     *
     * @param sysRoleId the value for sys_depart_role.SYS_ROLE_ID
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    public void setSysRoleId(Long sysRoleId) {
        this.sysRoleId = sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart_role.CREATE_TIME
     *
     * @return the value of sys_depart_role.CREATE_TIME
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart_role.CREATE_TIME
     *
     * @param createTime the value for sys_depart_role.CREATE_TIME
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart_role.CREATOR
     *
     * @return the value of sys_depart_role.CREATOR
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart_role.CREATOR
     *
     * @param creator the value for sys_depart_role.CREATOR
     *
     * @mbg.generated Wed Apr 18 10:29:05 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }
}