package com.chen.common.entity;

public class DicArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.GBT_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String gbtCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.P_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.AREA_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.AREA_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.P_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String pCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.AREA_LEVEL
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Boolean areaLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.STATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.GEO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String geo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.PINYIN
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String pinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.SHORT_PINYIN
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String shortPinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.ID
     *
     * @return the value of dic_area.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.ID
     *
     * @param id the value for dic_area.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.GBT_CODE
     *
     * @return the value of dic_area.GBT_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getGbtCode() {
        return gbtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.GBT_CODE
     *
     * @param gbtCode the value for dic_area.GBT_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setGbtCode(String gbtCode) {
        this.gbtCode = gbtCode == null ? null : gbtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.P_NAME
     *
     * @return the value of dic_area.P_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.P_NAME
     *
     * @param pName the value for dic_area.P_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.AREA_CODE
     *
     * @return the value of dic_area.AREA_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.AREA_CODE
     *
     * @param areaCode the value for dic_area.AREA_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.AREA_NAME
     *
     * @return the value of dic_area.AREA_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.AREA_NAME
     *
     * @param areaName the value for dic_area.AREA_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.P_CODE
     *
     * @return the value of dic_area.P_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.P_CODE
     *
     * @param pCode the value for dic_area.P_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.AREA_LEVEL
     *
     * @return the value of dic_area.AREA_LEVEL
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Boolean getAreaLevel() {
        return areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.AREA_LEVEL
     *
     * @param areaLevel the value for dic_area.AREA_LEVEL
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setAreaLevel(Boolean areaLevel) {
        this.areaLevel = areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.STATE
     *
     * @return the value of dic_area.STATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.STATE
     *
     * @param state the value for dic_area.STATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.GEO
     *
     * @return the value of dic_area.GEO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getGeo() {
        return geo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.GEO
     *
     * @param geo the value for dic_area.GEO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setGeo(String geo) {
        this.geo = geo == null ? null : geo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.PINYIN
     *
     * @return the value of dic_area.PINYIN
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.PINYIN
     *
     * @param pinyin the value for dic_area.PINYIN
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.SHORT_PINYIN
     *
     * @return the value of dic_area.SHORT_PINYIN
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getShortPinyin() {
        return shortPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.SHORT_PINYIN
     *
     * @param shortPinyin the value for dic_area.SHORT_PINYIN
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setShortPinyin(String shortPinyin) {
        this.shortPinyin = shortPinyin == null ? null : shortPinyin.trim();
    }
}