package com.chen.common.entity;

import java.util.Date;

public class DicTree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.SYS_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long sysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.SYS_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String sysName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.TYPE_KEY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String typeKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.TYPE_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.ALIAS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.LOGO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.VALUE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.LEAF_NODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Byte leafNode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.PAR_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String parCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.PAR_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String parName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.SORT
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.REMARK
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.EXTEND1
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String extend1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_tree.EXTEND2
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String extend2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.ID
     *
     * @return the value of dic_tree.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.ID
     *
     * @param id the value for dic_tree.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.SYS_ID
     *
     * @return the value of dic_tree.SYS_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.SYS_ID
     *
     * @param sysId the value for dic_tree.SYS_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setSysId(Long sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.SYS_NAME
     *
     * @return the value of dic_tree.SYS_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.SYS_NAME
     *
     * @param sysName the value for dic_tree.SYS_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.TYPE_KEY
     *
     * @return the value of dic_tree.TYPE_KEY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getTypeKey() {
        return typeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.TYPE_KEY
     *
     * @param typeKey the value for dic_tree.TYPE_KEY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setTypeKey(String typeKey) {
        this.typeKey = typeKey == null ? null : typeKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.TYPE_NAME
     *
     * @return the value of dic_tree.TYPE_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.TYPE_NAME
     *
     * @param typeName the value for dic_tree.TYPE_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.NAME
     *
     * @return the value of dic_tree.NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.NAME
     *
     * @param name the value for dic_tree.NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.ALIAS
     *
     * @return the value of dic_tree.ALIAS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.ALIAS
     *
     * @param alias the value for dic_tree.ALIAS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.CODE
     *
     * @return the value of dic_tree.CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.CODE
     *
     * @param code the value for dic_tree.CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.LOGO
     *
     * @return the value of dic_tree.LOGO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.LOGO
     *
     * @param logo the value for dic_tree.LOGO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.VALUE
     *
     * @return the value of dic_tree.VALUE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.VALUE
     *
     * @param value the value for dic_tree.VALUE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.LEAF_NODE
     *
     * @return the value of dic_tree.LEAF_NODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Byte getLeafNode() {
        return leafNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.LEAF_NODE
     *
     * @param leafNode the value for dic_tree.LEAF_NODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setLeafNode(Byte leafNode) {
        this.leafNode = leafNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.PAR_CODE
     *
     * @return the value of dic_tree.PAR_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getParCode() {
        return parCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.PAR_CODE
     *
     * @param parCode the value for dic_tree.PAR_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setParCode(String parCode) {
        this.parCode = parCode == null ? null : parCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.PAR_NAME
     *
     * @return the value of dic_tree.PAR_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getParName() {
        return parName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.PAR_NAME
     *
     * @param parName the value for dic_tree.PAR_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setParName(String parName) {
        this.parName = parName == null ? null : parName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.SORT
     *
     * @return the value of dic_tree.SORT
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.SORT
     *
     * @param sort the value for dic_tree.SORT
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.STATUS
     *
     * @return the value of dic_tree.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.STATUS
     *
     * @param status the value for dic_tree.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.REMARK
     *
     * @return the value of dic_tree.REMARK
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.REMARK
     *
     * @param remark the value for dic_tree.REMARK
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.CREATE_TIME
     *
     * @return the value of dic_tree.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.CREATE_TIME
     *
     * @param createTime the value for dic_tree.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.UPDATE_TIME
     *
     * @return the value of dic_tree.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.UPDATE_TIME
     *
     * @param updateTime the value for dic_tree.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.EXTEND1
     *
     * @return the value of dic_tree.EXTEND1
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.EXTEND1
     *
     * @param extend1 the value for dic_tree.EXTEND1
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_tree.EXTEND2
     *
     * @return the value of dic_tree.EXTEND2
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_tree.EXTEND2
     *
     * @param extend2 the value for dic_tree.EXTEND2
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }
}