package com.chen.common.entity;

import java.util.Date;

public class EnterpriseJobInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.ENTERPRISE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.JOB_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.PROVINCE_NO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String provinceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.CITY_NO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String cityNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.AREA_NO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String areaNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.WORK_ADDRESS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String workAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.RECRUIT_NUM
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Integer recruitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.WORK_NATURE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String workNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.SLARY_TYPE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String slaryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.SLARY_VALUE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String slaryValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.KEYWORD
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.DESCRIPTION
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.UPDATE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.EXTEND_STR1
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String extendStr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.EXTEND_STR2
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String extendStr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_job_info.EXTEND_STR3
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String extendStr3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.ID
     *
     * @return the value of enterprise_job_info.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.ID
     *
     * @param id the value for enterprise_job_info.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.ENTERPRISE_ID
     *
     * @return the value of enterprise_job_info.ENTERPRISE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.ENTERPRISE_ID
     *
     * @param enterpriseId the value for enterprise_job_info.ENTERPRISE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.JOB_NAME
     *
     * @return the value of enterprise_job_info.JOB_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.JOB_NAME
     *
     * @param jobName the value for enterprise_job_info.JOB_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.PROVINCE_NO
     *
     * @return the value of enterprise_job_info.PROVINCE_NO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getProvinceNo() {
        return provinceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.PROVINCE_NO
     *
     * @param provinceNo the value for enterprise_job_info.PROVINCE_NO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setProvinceNo(String provinceNo) {
        this.provinceNo = provinceNo == null ? null : provinceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.CITY_NO
     *
     * @return the value of enterprise_job_info.CITY_NO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getCityNo() {
        return cityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.CITY_NO
     *
     * @param cityNo the value for enterprise_job_info.CITY_NO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCityNo(String cityNo) {
        this.cityNo = cityNo == null ? null : cityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.AREA_NO
     *
     * @return the value of enterprise_job_info.AREA_NO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getAreaNo() {
        return areaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.AREA_NO
     *
     * @param areaNo the value for enterprise_job_info.AREA_NO
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setAreaNo(String areaNo) {
        this.areaNo = areaNo == null ? null : areaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.WORK_ADDRESS
     *
     * @return the value of enterprise_job_info.WORK_ADDRESS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getWorkAddress() {
        return workAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.WORK_ADDRESS
     *
     * @param workAddress the value for enterprise_job_info.WORK_ADDRESS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setWorkAddress(String workAddress) {
        this.workAddress = workAddress == null ? null : workAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.RECRUIT_NUM
     *
     * @return the value of enterprise_job_info.RECRUIT_NUM
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Integer getRecruitNum() {
        return recruitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.RECRUIT_NUM
     *
     * @param recruitNum the value for enterprise_job_info.RECRUIT_NUM
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setRecruitNum(Integer recruitNum) {
        this.recruitNum = recruitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.WORK_NATURE
     *
     * @return the value of enterprise_job_info.WORK_NATURE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getWorkNature() {
        return workNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.WORK_NATURE
     *
     * @param workNature the value for enterprise_job_info.WORK_NATURE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setWorkNature(String workNature) {
        this.workNature = workNature == null ? null : workNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.SLARY_TYPE
     *
     * @return the value of enterprise_job_info.SLARY_TYPE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getSlaryType() {
        return slaryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.SLARY_TYPE
     *
     * @param slaryType the value for enterprise_job_info.SLARY_TYPE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setSlaryType(String slaryType) {
        this.slaryType = slaryType == null ? null : slaryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.SLARY_VALUE
     *
     * @return the value of enterprise_job_info.SLARY_VALUE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getSlaryValue() {
        return slaryValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.SLARY_VALUE
     *
     * @param slaryValue the value for enterprise_job_info.SLARY_VALUE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setSlaryValue(String slaryValue) {
        this.slaryValue = slaryValue == null ? null : slaryValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.KEYWORD
     *
     * @return the value of enterprise_job_info.KEYWORD
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.KEYWORD
     *
     * @param keyword the value for enterprise_job_info.KEYWORD
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.DESCRIPTION
     *
     * @return the value of enterprise_job_info.DESCRIPTION
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.DESCRIPTION
     *
     * @param description the value for enterprise_job_info.DESCRIPTION
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.STATUS
     *
     * @return the value of enterprise_job_info.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.STATUS
     *
     * @param status the value for enterprise_job_info.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.CREATE_TIME
     *
     * @return the value of enterprise_job_info.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.CREATE_TIME
     *
     * @param createTime the value for enterprise_job_info.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.CREATOR_ID
     *
     * @return the value of enterprise_job_info.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.CREATOR_ID
     *
     * @param creatorId the value for enterprise_job_info.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.UPDATE_TIME
     *
     * @return the value of enterprise_job_info.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.UPDATE_TIME
     *
     * @param updateTime the value for enterprise_job_info.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.UPDATE_ID
     *
     * @return the value of enterprise_job_info.UPDATE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.UPDATE_ID
     *
     * @param updateId the value for enterprise_job_info.UPDATE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.EXTEND_STR1
     *
     * @return the value of enterprise_job_info.EXTEND_STR1
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getExtendStr1() {
        return extendStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.EXTEND_STR1
     *
     * @param extendStr1 the value for enterprise_job_info.EXTEND_STR1
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setExtendStr1(String extendStr1) {
        this.extendStr1 = extendStr1 == null ? null : extendStr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.EXTEND_STR2
     *
     * @return the value of enterprise_job_info.EXTEND_STR2
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getExtendStr2() {
        return extendStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.EXTEND_STR2
     *
     * @param extendStr2 the value for enterprise_job_info.EXTEND_STR2
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setExtendStr2(String extendStr2) {
        this.extendStr2 = extendStr2 == null ? null : extendStr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_job_info.EXTEND_STR3
     *
     * @return the value of enterprise_job_info.EXTEND_STR3
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getExtendStr3() {
        return extendStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_job_info.EXTEND_STR3
     *
     * @param extendStr3 the value for enterprise_job_info.EXTEND_STR3
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setExtendStr3(String extendStr3) {
        this.extendStr3 = extendStr3 == null ? null : extendStr3.trim();
    }
}