package com.chen.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EnterpriseJobRequirementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public EnterpriseJobRequirementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNull() {
            addCriterion("JOB_ID is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("JOB_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(Long value) {
            addCriterion("JOB_ID =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(Long value) {
            addCriterion("JOB_ID <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(Long value) {
            addCriterion("JOB_ID >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(Long value) {
            addCriterion("JOB_ID >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(Long value) {
            addCriterion("JOB_ID <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(Long value) {
            addCriterion("JOB_ID <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<Long> values) {
            addCriterion("JOB_ID in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<Long> values) {
            addCriterion("JOB_ID not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(Long value1, Long value2) {
            addCriterion("JOB_ID between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(Long value1, Long value2) {
            addCriterion("JOB_ID not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andWorkYearIsNull() {
            addCriterion("WORK_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andWorkYearIsNotNull() {
            addCriterion("WORK_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andWorkYearEqualTo(String value) {
            addCriterion("WORK_YEAR =", value, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearNotEqualTo(String value) {
            addCriterion("WORK_YEAR <>", value, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearGreaterThan(String value) {
            addCriterion("WORK_YEAR >", value, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_YEAR >=", value, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearLessThan(String value) {
            addCriterion("WORK_YEAR <", value, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearLessThanOrEqualTo(String value) {
            addCriterion("WORK_YEAR <=", value, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearLike(String value) {
            addCriterion("WORK_YEAR like", value, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearNotLike(String value) {
            addCriterion("WORK_YEAR not like", value, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearIn(List<String> values) {
            addCriterion("WORK_YEAR in", values, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearNotIn(List<String> values) {
            addCriterion("WORK_YEAR not in", values, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearBetween(String value1, String value2) {
            addCriterion("WORK_YEAR between", value1, value2, "workYear");
            return (Criteria) this;
        }

        public Criteria andWorkYearNotBetween(String value1, String value2) {
            addCriterion("WORK_YEAR not between", value1, value2, "workYear");
            return (Criteria) this;
        }

        public Criteria andMinDegreeIsNull() {
            addCriterion("MIN_DEGREE is null");
            return (Criteria) this;
        }

        public Criteria andMinDegreeIsNotNull() {
            addCriterion("MIN_DEGREE is not null");
            return (Criteria) this;
        }

        public Criteria andMinDegreeEqualTo(String value) {
            addCriterion("MIN_DEGREE =", value, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeNotEqualTo(String value) {
            addCriterion("MIN_DEGREE <>", value, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeGreaterThan(String value) {
            addCriterion("MIN_DEGREE >", value, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeGreaterThanOrEqualTo(String value) {
            addCriterion("MIN_DEGREE >=", value, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeLessThan(String value) {
            addCriterion("MIN_DEGREE <", value, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeLessThanOrEqualTo(String value) {
            addCriterion("MIN_DEGREE <=", value, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeLike(String value) {
            addCriterion("MIN_DEGREE like", value, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeNotLike(String value) {
            addCriterion("MIN_DEGREE not like", value, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeIn(List<String> values) {
            addCriterion("MIN_DEGREE in", values, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeNotIn(List<String> values) {
            addCriterion("MIN_DEGREE not in", values, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeBetween(String value1, String value2) {
            addCriterion("MIN_DEGREE between", value1, value2, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinDegreeNotBetween(String value1, String value2) {
            addCriterion("MIN_DEGREE not between", value1, value2, "minDegree");
            return (Criteria) this;
        }

        public Criteria andMinAgeIsNull() {
            addCriterion("MIN_AGE is null");
            return (Criteria) this;
        }

        public Criteria andMinAgeIsNotNull() {
            addCriterion("MIN_AGE is not null");
            return (Criteria) this;
        }

        public Criteria andMinAgeEqualTo(Integer value) {
            addCriterion("MIN_AGE =", value, "minAge");
            return (Criteria) this;
        }

        public Criteria andMinAgeNotEqualTo(Integer value) {
            addCriterion("MIN_AGE <>", value, "minAge");
            return (Criteria) this;
        }

        public Criteria andMinAgeGreaterThan(Integer value) {
            addCriterion("MIN_AGE >", value, "minAge");
            return (Criteria) this;
        }

        public Criteria andMinAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("MIN_AGE >=", value, "minAge");
            return (Criteria) this;
        }

        public Criteria andMinAgeLessThan(Integer value) {
            addCriterion("MIN_AGE <", value, "minAge");
            return (Criteria) this;
        }

        public Criteria andMinAgeLessThanOrEqualTo(Integer value) {
            addCriterion("MIN_AGE <=", value, "minAge");
            return (Criteria) this;
        }

        public Criteria andMinAgeIn(List<Integer> values) {
            addCriterion("MIN_AGE in", values, "minAge");
            return (Criteria) this;
        }

        public Criteria andMinAgeNotIn(List<Integer> values) {
            addCriterion("MIN_AGE not in", values, "minAge");
            return (Criteria) this;
        }

        public Criteria andMinAgeBetween(Integer value1, Integer value2) {
            addCriterion("MIN_AGE between", value1, value2, "minAge");
            return (Criteria) this;
        }

        public Criteria andMinAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("MIN_AGE not between", value1, value2, "minAge");
            return (Criteria) this;
        }

        public Criteria andMaxAgeIsNull() {
            addCriterion("MAX_AGE is null");
            return (Criteria) this;
        }

        public Criteria andMaxAgeIsNotNull() {
            addCriterion("MAX_AGE is not null");
            return (Criteria) this;
        }

        public Criteria andMaxAgeEqualTo(Integer value) {
            addCriterion("MAX_AGE =", value, "maxAge");
            return (Criteria) this;
        }

        public Criteria andMaxAgeNotEqualTo(Integer value) {
            addCriterion("MAX_AGE <>", value, "maxAge");
            return (Criteria) this;
        }

        public Criteria andMaxAgeGreaterThan(Integer value) {
            addCriterion("MAX_AGE >", value, "maxAge");
            return (Criteria) this;
        }

        public Criteria andMaxAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("MAX_AGE >=", value, "maxAge");
            return (Criteria) this;
        }

        public Criteria andMaxAgeLessThan(Integer value) {
            addCriterion("MAX_AGE <", value, "maxAge");
            return (Criteria) this;
        }

        public Criteria andMaxAgeLessThanOrEqualTo(Integer value) {
            addCriterion("MAX_AGE <=", value, "maxAge");
            return (Criteria) this;
        }

        public Criteria andMaxAgeIn(List<Integer> values) {
            addCriterion("MAX_AGE in", values, "maxAge");
            return (Criteria) this;
        }

        public Criteria andMaxAgeNotIn(List<Integer> values) {
            addCriterion("MAX_AGE not in", values, "maxAge");
            return (Criteria) this;
        }

        public Criteria andMaxAgeBetween(Integer value1, Integer value2) {
            addCriterion("MAX_AGE between", value1, value2, "maxAge");
            return (Criteria) this;
        }

        public Criteria andMaxAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("MAX_AGE not between", value1, value2, "maxAge");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeIsNull() {
            addCriterion("LANGUAGE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeIsNotNull() {
            addCriterion("LANGUAGE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeEqualTo(String value) {
            addCriterion("LANGUAGE_TYPE =", value, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeNotEqualTo(String value) {
            addCriterion("LANGUAGE_TYPE <>", value, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeGreaterThan(String value) {
            addCriterion("LANGUAGE_TYPE >", value, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeGreaterThanOrEqualTo(String value) {
            addCriterion("LANGUAGE_TYPE >=", value, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeLessThan(String value) {
            addCriterion("LANGUAGE_TYPE <", value, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeLessThanOrEqualTo(String value) {
            addCriterion("LANGUAGE_TYPE <=", value, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeLike(String value) {
            addCriterion("LANGUAGE_TYPE like", value, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeNotLike(String value) {
            addCriterion("LANGUAGE_TYPE not like", value, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeIn(List<String> values) {
            addCriterion("LANGUAGE_TYPE in", values, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeNotIn(List<String> values) {
            addCriterion("LANGUAGE_TYPE not in", values, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeBetween(String value1, String value2) {
            addCriterion("LANGUAGE_TYPE between", value1, value2, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageTypeNotBetween(String value1, String value2) {
            addCriterion("LANGUAGE_TYPE not between", value1, value2, "languageType");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelIsNull() {
            addCriterion("LANGUAGE_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelIsNotNull() {
            addCriterion("LANGUAGE_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelEqualTo(String value) {
            addCriterion("LANGUAGE_LEVEL =", value, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelNotEqualTo(String value) {
            addCriterion("LANGUAGE_LEVEL <>", value, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelGreaterThan(String value) {
            addCriterion("LANGUAGE_LEVEL >", value, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelGreaterThanOrEqualTo(String value) {
            addCriterion("LANGUAGE_LEVEL >=", value, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelLessThan(String value) {
            addCriterion("LANGUAGE_LEVEL <", value, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelLessThanOrEqualTo(String value) {
            addCriterion("LANGUAGE_LEVEL <=", value, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelLike(String value) {
            addCriterion("LANGUAGE_LEVEL like", value, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelNotLike(String value) {
            addCriterion("LANGUAGE_LEVEL not like", value, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelIn(List<String> values) {
            addCriterion("LANGUAGE_LEVEL in", values, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelNotIn(List<String> values) {
            addCriterion("LANGUAGE_LEVEL not in", values, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelBetween(String value1, String value2) {
            addCriterion("LANGUAGE_LEVEL between", value1, value2, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andLanguageLevelNotBetween(String value1, String value2) {
            addCriterion("LANGUAGE_LEVEL not between", value1, value2, "languageLevel");
            return (Criteria) this;
        }

        public Criteria andMajorIsNull() {
            addCriterion("MAJOR is null");
            return (Criteria) this;
        }

        public Criteria andMajorIsNotNull() {
            addCriterion("MAJOR is not null");
            return (Criteria) this;
        }

        public Criteria andMajorEqualTo(String value) {
            addCriterion("MAJOR =", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotEqualTo(String value) {
            addCriterion("MAJOR <>", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThan(String value) {
            addCriterion("MAJOR >", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThanOrEqualTo(String value) {
            addCriterion("MAJOR >=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThan(String value) {
            addCriterion("MAJOR <", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThanOrEqualTo(String value) {
            addCriterion("MAJOR <=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLike(String value) {
            addCriterion("MAJOR like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotLike(String value) {
            addCriterion("MAJOR not like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorIn(List<String> values) {
            addCriterion("MAJOR in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotIn(List<String> values) {
            addCriterion("MAJOR not in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorBetween(String value1, String value2) {
            addCriterion("MAJOR between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotBetween(String value1, String value2) {
            addCriterion("MAJOR not between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNull() {
            addCriterion("CREATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNotNull() {
            addCriterion("CREATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIdEqualTo(Long value) {
            addCriterion("CREATE_ID =", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotEqualTo(Long value) {
            addCriterion("CREATE_ID <>", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThan(Long value) {
            addCriterion("CREATE_ID >", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_ID >=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThan(Long value) {
            addCriterion("CREATE_ID <", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_ID <=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIn(List<Long> values) {
            addCriterion("CREATE_ID in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotIn(List<Long> values) {
            addCriterion("CREATE_ID not in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdBetween(Long value1, Long value2) {
            addCriterion("CREATE_ID between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_ID not between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdIsNull() {
            addCriterion("UPDATOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdIsNotNull() {
            addCriterion("UPDATOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdEqualTo(Long value) {
            addCriterion("UPDATOR_ID =", value, "updatorId");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdNotEqualTo(Long value) {
            addCriterion("UPDATOR_ID <>", value, "updatorId");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdGreaterThan(Long value) {
            addCriterion("UPDATOR_ID >", value, "updatorId");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATOR_ID >=", value, "updatorId");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdLessThan(Long value) {
            addCriterion("UPDATOR_ID <", value, "updatorId");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdLessThanOrEqualTo(Long value) {
            addCriterion("UPDATOR_ID <=", value, "updatorId");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdIn(List<Long> values) {
            addCriterion("UPDATOR_ID in", values, "updatorId");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdNotIn(List<Long> values) {
            addCriterion("UPDATOR_ID not in", values, "updatorId");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdBetween(Long value1, Long value2) {
            addCriterion("UPDATOR_ID between", value1, value2, "updatorId");
            return (Criteria) this;
        }

        public Criteria andUpdatorIdNotBetween(Long value1, Long value2) {
            addCriterion("UPDATOR_ID not between", value1, value2, "updatorId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 24 10:05:29 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_job_requirement
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}