package com.chen.common.entity;

import java.util.Date;

public class JobDeliveryRecond {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_delivery_recond.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_delivery_recond.TALENT_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long talentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_delivery_recond.JOB_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_delivery_recond.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long resumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_delivery_recond.ENTERPRISE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_delivery_recond.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_delivery_recond.DELETED
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_delivery_recond.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_delivery_recond.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long creatorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_delivery_recond.ID
     *
     * @return the value of job_delivery_recond.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_delivery_recond.ID
     *
     * @param id the value for job_delivery_recond.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_delivery_recond.TALENT_ID
     *
     * @return the value of job_delivery_recond.TALENT_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getTalentId() {
        return talentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_delivery_recond.TALENT_ID
     *
     * @param talentId the value for job_delivery_recond.TALENT_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setTalentId(Long talentId) {
        this.talentId = talentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_delivery_recond.JOB_ID
     *
     * @return the value of job_delivery_recond.JOB_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_delivery_recond.JOB_ID
     *
     * @param jobId the value for job_delivery_recond.JOB_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_delivery_recond.RESUME_ID
     *
     * @return the value of job_delivery_recond.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_delivery_recond.RESUME_ID
     *
     * @param resumeId the value for job_delivery_recond.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_delivery_recond.ENTERPRISE_ID
     *
     * @return the value of job_delivery_recond.ENTERPRISE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_delivery_recond.ENTERPRISE_ID
     *
     * @param enterpriseId the value for job_delivery_recond.ENTERPRISE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_delivery_recond.STATUS
     *
     * @return the value of job_delivery_recond.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_delivery_recond.STATUS
     *
     * @param status the value for job_delivery_recond.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_delivery_recond.DELETED
     *
     * @return the value of job_delivery_recond.DELETED
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_delivery_recond.DELETED
     *
     * @param deleted the value for job_delivery_recond.DELETED
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_delivery_recond.CREATE_TIME
     *
     * @return the value of job_delivery_recond.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_delivery_recond.CREATE_TIME
     *
     * @param createTime the value for job_delivery_recond.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_delivery_recond.CREATOR_ID
     *
     * @return the value of job_delivery_recond.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_delivery_recond.CREATOR_ID
     *
     * @param creatorId the value for job_delivery_recond.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }
}