package com.chen.common.entity;

import java.util.Date;

public class ResumeSkill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_skill.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_skill.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long resumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_skill.SKILL_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String skillName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_skill.SKILL_PROFICIENCY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String skillProficiency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_skill.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_skill.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_skill.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_skill.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_skill.ID
     *
     * @return the value of resume_skill.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_skill.ID
     *
     * @param id the value for resume_skill.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_skill.RESUME_ID
     *
     * @return the value of resume_skill.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_skill.RESUME_ID
     *
     * @param resumeId the value for resume_skill.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_skill.SKILL_NAME
     *
     * @return the value of resume_skill.SKILL_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getSkillName() {
        return skillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_skill.SKILL_NAME
     *
     * @param skillName the value for resume_skill.SKILL_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setSkillName(String skillName) {
        this.skillName = skillName == null ? null : skillName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_skill.SKILL_PROFICIENCY
     *
     * @return the value of resume_skill.SKILL_PROFICIENCY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getSkillProficiency() {
        return skillProficiency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_skill.SKILL_PROFICIENCY
     *
     * @param skillProficiency the value for resume_skill.SKILL_PROFICIENCY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setSkillProficiency(String skillProficiency) {
        this.skillProficiency = skillProficiency == null ? null : skillProficiency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_skill.STATUS
     *
     * @return the value of resume_skill.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_skill.STATUS
     *
     * @param status the value for resume_skill.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_skill.CREATE_TIME
     *
     * @return the value of resume_skill.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_skill.CREATE_TIME
     *
     * @param createTime the value for resume_skill.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_skill.CREATOR_ID
     *
     * @return the value of resume_skill.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_skill.CREATOR_ID
     *
     * @param creatorId the value for resume_skill.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_skill.UPDATE_TIME
     *
     * @return the value of resume_skill.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_skill.UPDATE_TIME
     *
     * @param updateTime the value for resume_skill.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}