package com.chen.common.entity;

import java.util.Date;

public class ResumeCertificate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_certificate.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_certificate.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long resumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_certificate.CERTIFICATE_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String certificateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_certificate.CERTIFICATE_SCORE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Double certificateScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_certificate.CERTIFICATE_DATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date certificateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_certificate.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_certificate.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_certificate.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_certificate.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_certificate.ID
     *
     * @return the value of resume_certificate.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_certificate.ID
     *
     * @param id the value for resume_certificate.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_certificate.RESUME_ID
     *
     * @return the value of resume_certificate.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_certificate.RESUME_ID
     *
     * @param resumeId the value for resume_certificate.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_certificate.CERTIFICATE_NAME
     *
     * @return the value of resume_certificate.CERTIFICATE_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getCertificateName() {
        return certificateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_certificate.CERTIFICATE_NAME
     *
     * @param certificateName the value for resume_certificate.CERTIFICATE_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCertificateName(String certificateName) {
        this.certificateName = certificateName == null ? null : certificateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_certificate.CERTIFICATE_SCORE
     *
     * @return the value of resume_certificate.CERTIFICATE_SCORE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Double getCertificateScore() {
        return certificateScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_certificate.CERTIFICATE_SCORE
     *
     * @param certificateScore the value for resume_certificate.CERTIFICATE_SCORE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCertificateScore(Double certificateScore) {
        this.certificateScore = certificateScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_certificate.CERTIFICATE_DATE
     *
     * @return the value of resume_certificate.CERTIFICATE_DATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getCertificateDate() {
        return certificateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_certificate.CERTIFICATE_DATE
     *
     * @param certificateDate the value for resume_certificate.CERTIFICATE_DATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCertificateDate(Date certificateDate) {
        this.certificateDate = certificateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_certificate.STATUS
     *
     * @return the value of resume_certificate.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_certificate.STATUS
     *
     * @param status the value for resume_certificate.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_certificate.CREATE_TIME
     *
     * @return the value of resume_certificate.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_certificate.CREATE_TIME
     *
     * @param createTime the value for resume_certificate.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_certificate.CREATOR_ID
     *
     * @return the value of resume_certificate.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_certificate.CREATOR_ID
     *
     * @param creatorId the value for resume_certificate.CREATOR_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_certificate.UPDATE_TIME
     *
     * @return the value of resume_certificate.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_certificate.UPDATE_TIME
     *
     * @param updateTime the value for resume_certificate.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}