package com.chen.common.entity;

import java.util.Date;

public class ResumeWorkExp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long resumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.COMPANY_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.POSITION_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.START_DATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.END_DATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.BUSINESS_TYPE_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String businessTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.SALARY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Short salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.WORK_CONTENT
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String workContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.WORK_DEPART
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String workDepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.CREATE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.REMARK1
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String remark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.REMARK2
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String remark2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.REMARK3
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String remark3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.WORK_PERFORMANCE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String workPerformance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.COMPANY_INDUSTRY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private String companyIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.COMPANY_SIZE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Integer companySize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.HIDE_IT
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Byte hideIt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_work_exp.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.ID
     *
     * @return the value of resume_work_exp.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.ID
     *
     * @param id the value for resume_work_exp.ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.RESUME_ID
     *
     * @return the value of resume_work_exp.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.RESUME_ID
     *
     * @param resumeId the value for resume_work_exp.RESUME_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.COMPANY_NAME
     *
     * @return the value of resume_work_exp.COMPANY_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.COMPANY_NAME
     *
     * @param companyName the value for resume_work_exp.COMPANY_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.POSITION_NAME
     *
     * @return the value of resume_work_exp.POSITION_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.POSITION_NAME
     *
     * @param positionName the value for resume_work_exp.POSITION_NAME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.START_DATE
     *
     * @return the value of resume_work_exp.START_DATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.START_DATE
     *
     * @param startDate the value for resume_work_exp.START_DATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.END_DATE
     *
     * @return the value of resume_work_exp.END_DATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.END_DATE
     *
     * @param endDate the value for resume_work_exp.END_DATE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.BUSINESS_TYPE_CODE
     *
     * @return the value of resume_work_exp.BUSINESS_TYPE_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getBusinessTypeCode() {
        return businessTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.BUSINESS_TYPE_CODE
     *
     * @param businessTypeCode the value for resume_work_exp.BUSINESS_TYPE_CODE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setBusinessTypeCode(String businessTypeCode) {
        this.businessTypeCode = businessTypeCode == null ? null : businessTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.SALARY
     *
     * @return the value of resume_work_exp.SALARY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Short getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.SALARY
     *
     * @param salary the value for resume_work_exp.SALARY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setSalary(Short salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.WORK_CONTENT
     *
     * @return the value of resume_work_exp.WORK_CONTENT
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getWorkContent() {
        return workContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.WORK_CONTENT
     *
     * @param workContent the value for resume_work_exp.WORK_CONTENT
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setWorkContent(String workContent) {
        this.workContent = workContent == null ? null : workContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.WORK_DEPART
     *
     * @return the value of resume_work_exp.WORK_DEPART
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getWorkDepart() {
        return workDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.WORK_DEPART
     *
     * @param workDepart the value for resume_work_exp.WORK_DEPART
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setWorkDepart(String workDepart) {
        this.workDepart = workDepart == null ? null : workDepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.CREATE_TIME
     *
     * @return the value of resume_work_exp.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.CREATE_TIME
     *
     * @param createTime the value for resume_work_exp.CREATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.UPDATE_TIME
     *
     * @return the value of resume_work_exp.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.UPDATE_TIME
     *
     * @param updateTime the value for resume_work_exp.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.CREATE_ID
     *
     * @return the value of resume_work_exp.CREATE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.CREATE_ID
     *
     * @param createId the value for resume_work_exp.CREATE_ID
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.REMARK1
     *
     * @return the value of resume_work_exp.REMARK1
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.REMARK1
     *
     * @param remark1 the value for resume_work_exp.REMARK1
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.REMARK2
     *
     * @return the value of resume_work_exp.REMARK2
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.REMARK2
     *
     * @param remark2 the value for resume_work_exp.REMARK2
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.REMARK3
     *
     * @return the value of resume_work_exp.REMARK3
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.REMARK3
     *
     * @param remark3 the value for resume_work_exp.REMARK3
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.WORK_PERFORMANCE
     *
     * @return the value of resume_work_exp.WORK_PERFORMANCE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getWorkPerformance() {
        return workPerformance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.WORK_PERFORMANCE
     *
     * @param workPerformance the value for resume_work_exp.WORK_PERFORMANCE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setWorkPerformance(String workPerformance) {
        this.workPerformance = workPerformance == null ? null : workPerformance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.COMPANY_INDUSTRY
     *
     * @return the value of resume_work_exp.COMPANY_INDUSTRY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public String getCompanyIndustry() {
        return companyIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.COMPANY_INDUSTRY
     *
     * @param companyIndustry the value for resume_work_exp.COMPANY_INDUSTRY
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCompanyIndustry(String companyIndustry) {
        this.companyIndustry = companyIndustry == null ? null : companyIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.COMPANY_SIZE
     *
     * @return the value of resume_work_exp.COMPANY_SIZE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Integer getCompanySize() {
        return companySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.COMPANY_SIZE
     *
     * @param companySize the value for resume_work_exp.COMPANY_SIZE
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setCompanySize(Integer companySize) {
        this.companySize = companySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.HIDE_IT
     *
     * @return the value of resume_work_exp.HIDE_IT
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Byte getHideIt() {
        return hideIt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.HIDE_IT
     *
     * @param hideIt the value for resume_work_exp.HIDE_IT
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setHideIt(Byte hideIt) {
        this.hideIt = hideIt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_work_exp.STATUS
     *
     * @return the value of resume_work_exp.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_work_exp.STATUS
     *
     * @param status the value for resume_work_exp.STATUS
     *
     * @mbg.generated Sat Mar 24 10:05:29 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}